package wt

// Pre-push hook support (T-01KYDNN): the workspace verify commands gate
// automated done transitions; a HUMAN push bypasses them and burns a
// runner on code that may not build. The hook closes that hole with the
// SAME commands from the same config — one definition of the local gate.
// Consent model: recommendation over imposition — the server never writes
// into .git by default; InstallPrePushHook runs only on the operator's
// explicit `spectackle hook install`.

import (
	"os"
	"path/filepath"
	"strings"
)

// prePushHook shells to the binary on PATH so the hook inherits config
// changes and rebuilds without rewriting.
const prePushHook = `#!/bin/sh
# generated by 'spectackle hook install' — runs the workspace verify gate
# (config.yaml 'verify' commands) before every push. Requires spectackle
# on PATH. Remove this file to opt out.
exec spectackle verify -root "$(git rev-parse --show-toplevel)"
`

// HookPath returns the repo's pre-push hook path, honoring core.hooksPath
// being ABSENT (the default layout); a custom hooksPath repo is left to
// its owner — the recommendation hint stays silent there.
func HookPath(dir string) string {
	return filepath.Join(dir, ".git", "hooks", "pre-push")
}

// HookReferencesSpectackle reports whether an existing pre-push hook
// already runs the spectackle gate.
func HookReferencesSpectackle(dir string) bool {
	raw, err := os.ReadFile(HookPath(dir))
	return err == nil && strings.Contains(string(raw), "spectackle")
}

// InstallPrePushHook writes the hook, refusing to clobber a foreign one —
// an existing hook without a spectackle reference belongs to the operator.
func InstallPrePushHook(dir string) error {
	p := HookPath(dir)
	if raw, err := os.ReadFile(p); err == nil && !strings.Contains(string(raw), "spectackle") {
		return os.ErrExist
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, []byte(prePushHook), 0o755)
}
