package mcpserver

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/jxsl13/spectackle/internal/item"
	"github.com/jxsl13/spectackle/internal/lifecycle"
)

// commands generates harness-native entry points (slash commands / prompt
// files / AGENTS.md sections) from the two templates below, so every
// supported coding-agent harness gets the same two-mode ($ARGUMENTS empty =
// state snapshot, non-empty = full SDD lifecycle) dispatch that
// .claude/commands/spectackle.md pioneered — without hand-maintaining N
// per-harness copies. detect: sniff which harnesses are already wired into
// the repo from filesystem markers. gen: (re)write the dialect files for a
// harness set resolved arg > detection > elicitation (MCP-003 family): the
// user answers a native checkbox form, or — no UI, decline, or a different
// harness — an `adr` item is minted and left open exactly like
// decideAsk (decide.go), never blocking the caller.
//
// gen's command set defaults to the three load-bearing commands (entry
// point, state, generate) — enough to run the lifecycle and to ask for more.
// The six exploration commands (find, get, research, swarm, export, merge)
// are opt-in: pass all=true for every command, or commands=<names> for a
// specific subset (either unions with the default three, never replaces
// them — the default set is always present once requested at all).
type commandsIn struct {
	Op       string   `json:"op" jsonschema:"detect|gen|install-hooks"`
	Harness  []string `json:"harness,omitempty" jsonschema:"claude|copilot|codex|kimi — omit to auto-detect"`
	Commands []string `json:"commands,omitempty" jsonschema:"gen only: opt-in command names to add on top of the default three (find|get|research|swarm|export|merge) — omit for defaults only"`
	All      bool     `json:"all,omitempty" jsonschema:"gen only: generate every command (default three plus all six opt-in exploration commands)"`
}

//go:embed templates/commands/*.tmpl
var commandTemplateFS embed.FS

// commandTemplates parses once at package init: a bad embedded template is a
// build-time bug, not a runtime one.
var commandTemplates = template.Must(template.ParseFS(commandTemplateFS, "templates/commands/*.tmpl"))

//go:embed templates/hooks/*.tmpl
var hookTemplateFS embed.FS

// hookTemplates parses once at package init, same reasoning as
// commandTemplates: a bad embedded hook template is a build-time bug.
var hookTemplates = template.Must(template.ParseFS(hookTemplateFS, "templates/hooks/*.tmpl"))

// commandsData is the template data — {Binary, Tool} are both "spectackle"
// today; kept as two fields (not one) because the binary name (CLI, `/x-state`
// slash-command stem) and the MCP tool/server name are conceptually distinct
// even though this repo's install happens to give them the same value.
type commandsData struct {
	Binary string
	Tool   string
	// RepoURL is the module's https:// repository URL, derived the same way
	// the instructions manifest derives it (moduleRepoURL). Generated
	// slash-command surfaces are read by agents that never see the
	// initialize handshake, so the defect-report destination has to be named
	// here too rather than left as "its repository".
	RepoURL string
}

// generatedHeader is stamped into every artifact `commands gen` writes —
// hand-edits belong in the templates, not the generated files.
const generatedHeader = "<!-- generated by spectackle `commands` — edit internal/mcpserver/templates, not this file -->"

// hookGeneratedHeader is the POSIX-sh equivalent of generatedHeader (an
// HTML comment isn't valid shell) — the first line of the rendered
// pre-commit.tmpl body and the marker `install-hooks` checks for before
// ever overwriting a pre-existing hooks/pre-commit file: present means
// "ours, safe to regenerate"; absent means "the repo owner's, refuse".
const hookGeneratedHeader = "# generated by spectackle `commands install-hooks` — edit internal/mcpserver/templates/hooks, not this file"

// sectionBegin/sectionEnd delimit the managed block commands gen writes into
// AGENTS.md for the codex/kimi dialect — everything outside the markers is
// the repo owner's, never touched.
const (
	sectionBegin = "<!-- spectackle:commands:begin -->"
	sectionEnd   = "<!-- spectackle:commands:end -->"
)

var validHarnesses = map[string]bool{"claude": true, "copilot": true, "codex": true, "kimi": true}

// commandSpec describes one generated command. Name is the slash-command
// stem after the binary — empty for the main lifecycle entry point, which
// gets the bare "<binary>.md" filename instead of "<binary>-.md". Heading is
// the AGENTS.md managed-section heading word (codex/kimi dialect); it
// mirrors Name except for the entry point, which keeps the historical
// "workflow" heading. Description is the claude dialect's frontmatter
// `description:` line and doubles as the copilot dialect's doc comment.
// Default marks the load-bearing commands `gen` emits without an explicit
// all=/commands= argument: the entry point, state, and generate itself —
// generate must be default, otherwise a user with only the default set has
// no way to ask for the rest short of reading source.
type commandSpec struct {
	Name        string
	Heading     string
	Template    string
	Description string
	Default     bool
}

// commandSpecs is the full generated-command set, in the order every
// dialect writer emits them. Adding a command means: one new template file
// under templates/commands, one entry here — nothing else changes.
var commandSpecs = []commandSpec{
	{Name: "", Heading: "workflow", Template: "workflow.md.tmpl", Default: true,
		Description: "spectackle entry point — bare = state snapshot, with a requirement = full SDD lifecycle"},
	{Name: "state", Heading: "state", Template: "state.md.tmpl", Default: true,
		Description: "Render the current spectackle state (explicit alias for bare /spectackle)"},
	{Name: "generate", Heading: "generate", Template: "generate.md.tmpl", Default: true,
		Description: "(Re)generate spectackle's own slash commands/prompts — default three, or all=/commands= for the six exploration commands"},
	{Name: "find", Heading: "find", Template: "find.md.tmpl",
		Description: "Search records — code, rules, spec prose, or lifecycle items (unified `find`)"},
	{Name: "get", Heading: "get", Template: "get.md.tmpl",
		Description: "Read one record by ID — item, rule, node, dir, file or section"},
	{Name: "research", Heading: "research", Template: "research.md.tmpl",
		Description: "Server-aggregated, read-only research pack for a topic"},
	{Name: "swarm", Heading: "swarm", Template: "swarm.md.tmpl",
		Description: "Sibling awareness — agents, leases, worktrees, recent learnings"},
	{Name: "export", Heading: "export", Template: "export.md.tmpl",
		Description: "Export this workspace's knowledge (rules, ADRs, intent) as a portable artifact"},
	{Name: "merge", Heading: "merge", Template: "merge.md.tmpl",
		Description: "Merge several knowledge artifacts into one condensate, reporting conflicts"},
}

// defaultCommandSpecs returns the Default-marked subset of commandSpecs, in
// commandSpecs order.
func defaultCommandSpecs() []commandSpec {
	var out []commandSpec
	for _, spec := range commandSpecs {
		if spec.Default {
			out = append(out, spec)
		}
	}
	return out
}

// commandSpecByName finds a commandSpec by its Name field. The entry point
// (Name == "") is unreachable through this lookup on purpose — it has no
// name a caller could type, and it is already in the default set.
func commandSpecByName(name string) (commandSpec, bool) {
	for _, spec := range commandSpecs {
		if spec.Name == name {
			return spec, true
		}
	}
	return commandSpec{}, false
}

// selectCommandSpecs resolves gen's command set: the default three, plus
// whatever commandsArg/all ask for on top. all=true (or the literal name
// "all" inside commandsArg, for callers that only have a list to work with)
// short-circuits to the full commandSpecs set. Anything else is validated
// against commandSpecByName and unioned with the defaults — never a
// replacement, since the default three staying present is what makes the
// opt-in set discoverable in the first place. Return order always follows
// commandSpecs, not argument order, so downstream headings/sections stay
// coherent regardless of how commandsArg was written.
func selectCommandSpecs(commandsArg []string, all bool) ([]commandSpec, error) {
	if all {
		return append([]commandSpec(nil), commandSpecs...), nil
	}
	selected := map[string]bool{}
	for _, spec := range defaultCommandSpecs() {
		selected[spec.Heading] = true
	}
	for _, name := range commandsArg {
		name = strings.ToLower(strings.TrimSpace(name))
		if name == "" {
			continue
		}
		if name == "all" {
			return append([]commandSpec(nil), commandSpecs...), nil
		}
		spec, ok := commandSpecByName(name)
		if !ok {
			return nil, fmt.Errorf("unknown command %q (want find|get|research|swarm|export|merge)", name)
		}
		selected[spec.Heading] = true
	}
	var out []commandSpec
	for _, spec := range commandSpecs {
		if selected[spec.Heading] {
			out = append(out, spec)
		}
	}
	return out, nil
}

func (s *Server) commands(ctx context.Context, req *mcp.CallToolRequest, in commandsIn) (*mcp.CallToolResult, any, error) {
	switch in.Op {
	case "detect":
		return s.commandsDetect()
	case "gen":
		return s.commandsGen(ctx, req, in)
	case "install-hooks":
		return s.commandsInstallHooks()
	}
	return text("! ARG E - op must be detect|gen|install-hooks")
}

// ---- detect ----

// harnessHit is one root-marker match: which harness it identifies and the
// path that triggered it.
type harnessHit struct{ harness, marker string }

// detectHarnesses sniffs the workspace root for each supported harness's
// native marker. AGENTS.md is consumed by both codex and kimi, so its
// presence yields two hits, not one — a repo with only AGENTS.md and no
// .codex/.kimi dirs is still unambiguous about wanting both dialects kept in
// sync.
func detectHarnesses(root string) []harnessHit {
	var hits []harnessHit
	if isDir(filepath.Join(root, ".claude")) {
		hits = append(hits, harnessHit{"claude", ".claude/"})
	}
	if isDir(filepath.Join(root, ".github", "prompts")) {
		hits = append(hits, harnessHit{"copilot", ".github/prompts/"})
	} else if isFile(filepath.Join(root, ".github", "copilot-instructions.md")) {
		hits = append(hits, harnessHit{"copilot", ".github/copilot-instructions.md"})
	}
	if isDir(filepath.Join(root, ".codex")) {
		hits = append(hits, harnessHit{"codex", ".codex/"})
	}
	if isDir(filepath.Join(root, ".kimi")) {
		hits = append(hits, harnessHit{"kimi", ".kimi/"})
	}
	if isFile(filepath.Join(root, "AGENTS.md")) {
		hits = append(hits, harnessHit{"codex", "AGENTS.md"}, harnessHit{"kimi", "AGENTS.md"})
	}
	return hits
}

func isDir(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && fi.IsDir()
}

func isFile(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && !fi.IsDir()
}

func (s *Server) commandsDetect() (*mcp.CallToolResult, any, error) {
	hits := detectHarnesses(s.ws.Dir)
	if len(hits) == 0 {
		return text("nf harness — pass harness=... or answer the decision\n")
	}
	var b strings.Builder
	for _, h := range hits {
		fmt.Fprintf(&b, "h %s %s\n", h.harness, h.marker)
	}
	return text(b.String())
}

// ---- gen ----

const commandsQuestion = "which harnesses should `commands` generate for? (claude, copilot, codex, kimi)"

func (s *Server) commandsGen(ctx context.Context, req *mcp.CallToolRequest, in commandsIn) (*mcp.CallToolResult, any, error) {
	harnesses, err := normalizeHarnesses(in.Harness)
	if err != nil {
		return text("! ARG E - " + err.Error())
	}
	if len(harnesses) == 0 {
		harnesses = dedupHarnessHits(detectHarnesses(s.ws.Dir))
	}
	if len(harnesses) == 0 {
		selected, ok := s.commandsElicit(ctx, req)
		if !ok {
			return s.commandsMintDecision()
		}
		if len(selected) == 0 {
			return text("! ARG E - no harness selected")
		}
		harnesses = selected
	}

	specs, err := selectCommandSpecs(in.Commands, in.All)
	if err != nil {
		return text("! ARG E - " + err.Error())
	}

	data := commandsData{Binary: "spectackle", Tool: "spectackle", RepoURL: moduleRepoURL()}
	bodies := make(map[string]string, len(specs))
	for _, spec := range specs {
		body, err := renderCommandTemplate(spec.Template, data)
		if err != nil {
			return nil, nil, err
		}
		bodies[spec.Template] = body
	}

	var b strings.Builder
	for _, h := range harnesses {
		files, err := writeDialect(s.ws.Dir, h, specs, data, bodies)
		if err != nil {
			return nil, nil, err
		}
		for _, f := range files {
			fmt.Fprintf(&b, "ok gen %s %s\n", h, f)
		}
	}
	// codegen, not spec history: one coord event so siblings see it happened
	// in realtime, but no journal write — these files aren't .spectackle state.
	_ = s.cd.Emit("commands", strings.Join(harnesses, ","), s.ws.Dir)
	return text(b.String())
}

// normalizeHarnesses validates and dedupes an explicit harness= argument,
// preserving first-seen order.
func normalizeHarnesses(in []string) ([]string, error) {
	var out []string
	seen := map[string]bool{}
	for _, h := range in {
		h = strings.ToLower(strings.TrimSpace(h))
		if h == "" {
			continue
		}
		if !validHarnesses[h] {
			return nil, fmt.Errorf("unknown harness %q (want claude|copilot|codex|kimi)", h)
		}
		if !seen[h] {
			seen[h] = true
			out = append(out, h)
		}
	}
	return out, nil
}

// dedupHarnessHits collapses detectHarnesses' hits (which may name the same
// harness twice, e.g. AGENTS.md hitting both codex and kimi) to a unique,
// first-seen-order harness list.
func dedupHarnessHits(hits []harnessHit) []string {
	var out []string
	seen := map[string]bool{}
	for _, h := range hits {
		if !seen[h.harness] {
			seen[h.harness] = true
			out = append(out, h.harness)
		}
	}
	return out
}

// commandsElicit renders a native checkbox form (one boolean per harness) —
// the same req.Session.Elicit mechanism elicitSlots (tools.go) and decideAsk
// (decide.go) use — and returns the harnesses the user checked. ok is false
// on any non-accept outcome (no elicitation capability, decline, cancel,
// transport error): the caller falls back to minting an adr item instead of
// blocking.
func (s *Server) commandsElicit(ctx context.Context, req *mcp.CallToolRequest) ([]string, bool) {
	props := map[string]any{
		"claude":  map[string]any{"type": "boolean", "description": "Claude Code — .claude/commands/*.md"},
		"copilot": map[string]any{"type": "boolean", "description": "GitHub Copilot — .github/prompts/*.prompt.md"},
		"codex":   map[string]any{"type": "boolean", "description": "Codex — AGENTS.md managed section"},
		"kimi":    map[string]any{"type": "boolean", "description": "Kimi — AGENTS.md managed section"},
	}
	res, err := req.Session.Elicit(ctx, &mcp.ElicitParams{
		Message: "spectackle: " + commandsQuestion,
		RequestedSchema: map[string]any{
			"type": "object", "properties": props,
		},
	})
	if err != nil || res.Action != "accept" {
		return nil, false
	}
	var out []string
	for _, h := range []string{"claude", "copilot", "codex", "kimi"} {
		if b, _ := res.Content[h].(bool); b {
			out = append(out, h)
		}
	}
	return out, true
}

// commandsMintDecision is the elicitation-declined/no-UI fallback: mint a
// free-text `adr` item and leave it open (state=submitted), exactly
// like decideAsk (decide.go) does when its own elicitation attempt fails —
// duplicated minimally here rather than calling decideAsk itself, since that
// would fire a second, differently-shaped elicitation round after ours
// already came back empty.
func (s *Server) commandsMintDecision() (*mcp.CallToolResult, any, error) {
	body := "kind: text\noptions: free text — comma-separated subset of claude,copilot,codex,kimi"
	d, err := lifecycle.Draft(s.ws, s.minter(), "adr", commandsQuestion, body, "", "", nil)
	if err != nil {
		return text("! ARG E - " + err.Error())
	}
	if _, err := lifecycle.Move(s.ws, d.ID, item.StateSubmitted, ""); err != nil {
		return nil, nil, err
	}
	s.scan.MarkDirty()
	_ = s.cd.Emit("decide", d.ID, "ask "+commandsQuestion)
	return text(fmt.Sprintf("need decision %s %s\n", d.ID, commandsQuestion))
}

// ---- install-hooks ----

// gitCommonDir resolves the repository's common git directory for dir, as
// an absolute path. This is where a linked worktree's hooks/ actually
// lives too — git looks hooks up in the common dir for every worktree, not
// just the main checkout — so writing the generated pre-commit hook there
// once covers all of them (MCP-015). Not a git repo (or git missing):
// error.
func gitCommonDir(dir string) (string, error) {
	out, err := exec.Command("git", "-C", dir, "rev-parse", "--path-format=absolute", "--git-common-dir").Output()
	if err != nil {
		return "", fmt.Errorf("git rev-parse --git-common-dir: %w", err)
	}
	commonDir := strings.TrimSpace(string(out))
	if commonDir == "" {
		return "", fmt.Errorf("git rev-parse --git-common-dir: empty output")
	}
	// --path-format=absolute is git >= 2.31; fall back to resolving a
	// relative answer against dir for older installs rather than failing.
	if !filepath.IsAbs(commonDir) {
		commonDir = filepath.Join(dir, commonDir)
	}
	return commonDir, nil
}

// commandsInstallHooks (re)writes the repository's pre-commit hook from
// templates/hooks/pre-commit.tmpl to <git-common-dir>/hooks/pre-commit,
// mode 0o755 — a non-executable hook is silently ignored by git, so the
// mode is asserted on every run, not just the first. Idempotent: a second
// run finds its own hookGeneratedHeader marker and freely regenerates.
// Refuses (without touching the file) when hooks/pre-commit already exists
// and does NOT carry that marker — it belongs to the repo owner, not to
// spectackle.
func (s *Server) commandsInstallHooks() (*mcp.CallToolResult, any, error) {
	commonDir, err := gitCommonDir(s.ws.Dir)
	if err != nil {
		return text("! ARG E - not a git repository: " + err.Error())
	}

	body, err := renderHookTemplate("pre-commit.tmpl", commandsData{Binary: "spectackle", Tool: "spectackle"})
	if err != nil {
		return nil, nil, err
	}

	hooksDir := filepath.Join(commonDir, "hooks")
	path := filepath.Join(hooksDir, "pre-commit")
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		if !strings.Contains(string(existing), hookGeneratedHeader) {
			return text("! ARG E - refusing to overwrite " + path + " — an existing pre-commit hook not written by spectackle (no generated marker); remove or relocate it first")
		}
	case os.IsNotExist(err):
		// nothing there yet — fine, write fresh below.
	default:
		return nil, nil, err
	}

	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return nil, nil, err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return nil, nil, err
	}
	// os.WriteFile only applies its mode bits at creation time (subject to
	// umask); assert 0o755 explicitly so a second run over a file whose
	// mode drifted (or a restrictive umask on the first run) still leaves
	// an executable hook — the worst failure mode here is a hook git
	// silently ignores.
	if err := os.Chmod(path, 0o755); err != nil {
		return nil, nil, err
	}

	return text("ok hooks pre-commit " + relToRoot(s.ws.Dir, path) + "\n")
}

// renderHookTemplate mirrors renderCommandTemplate but over the separate
// templates/hooks/*.tmpl set (a different embed.FS/directory, kept apart
// from the slash-command dialects it has nothing to do with).
func renderHookTemplate(name string, data commandsData) (string, error) {
	var buf bytes.Buffer
	if err := hookTemplates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// ---- template rendering + per-dialect writers ----

func renderCommandTemplate(name string, data commandsData) (string, error) {
	var buf bytes.Buffer
	if err := commandTemplates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// writeDialect dispatches to the per-harness writer and returns the
// repo-relative paths written, for the `ok gen <harness> <path>` result
// lines. specs is this run's selected command set (defaults, or defaults
// plus opt-in extras); bodies is keyed by commandSpec.Template, one rendered
// body per spec in specs.
func writeDialect(root, harness string, specs []commandSpec, data commandsData, bodies map[string]string) ([]string, error) {
	switch harness {
	case "claude":
		return writeClaudeDialect(root, specs, data, bodies)
	case "copilot":
		return writeCopilotDialect(root, specs, data, bodies)
	case "codex", "kimi":
		return writeAgentsSection(root, specs, bodies)
	}
	return nil, fmt.Errorf("unknown harness %q", harness)
}

// claudeFilename/copilotFilename apply the naming convention: the main
// entry point (Name == "") is the bare "<binary>.md" / "<binary>.prompt.md";
// every other command is "<binary>-<name>.md" / "<binary>-<name>.prompt.md".
func claudeFilename(binary, name string) string {
	if name == "" {
		return binary + ".md"
	}
	return binary + "-" + name + ".md"
}

func copilotFilename(binary, name string) string {
	if name == "" {
		return binary + ".prompt.md"
	}
	return binary + "-" + name + ".prompt.md"
}

// writeClaudeDialect regenerates .claude/commands/*.md — one file per spec
// in specs, same frontmatter shape (description:) the hand-written
// originals carried, plus the generated-header comment. Only the files for
// specs in this run are touched: a command left out of specs (opt-in,
// not requested this time) keeps whatever file it already has on disk —
// gen adds and overwrites, it never deletes.
func writeClaudeDialect(root string, specs []commandSpec, data commandsData, bodies map[string]string) ([]string, error) {
	dir := filepath.Join(root, ".claude", "commands")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	var files []string
	for _, spec := range specs {
		content := "---\ndescription: " + spec.Description + "\n---\n\n" +
			generatedHeader + "\n\n" + bodies[spec.Template]
		p := filepath.Join(dir, claudeFilename(data.Binary, spec.Name))
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return nil, err
		}
		files = append(files, relToRoot(root, p))
	}
	return files, nil
}

// writeCopilotDialect writes .github/prompts/*.prompt.md — one file per
// spec in specs, with GitHub Copilot's `mode: agent` frontmatter. Same
// add/overwrite-only, never-delete behavior as writeClaudeDialect.
func writeCopilotDialect(root string, specs []commandSpec, data commandsData, bodies map[string]string) ([]string, error) {
	dir := filepath.Join(root, ".github", "prompts")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	var files []string
	for _, spec := range specs {
		content := "---\nmode: agent\n---\n\n" + generatedHeader + "\n\n" + bodies[spec.Template]
		p := filepath.Join(dir, copilotFilename(data.Binary, spec.Name))
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return nil, err
		}
		files = append(files, relToRoot(root, p))
	}
	return files, nil
}

// writeAgentsSection creates or updates AGENTS.md's spectackle-managed
// section (codex and kimi share it — both harnesses consume AGENTS.md) with
// one "## spectackle <heading>" subsection per spec in specs, in
// commandSpecs order — coherent instead of appended blindly. Only the text
// between sectionBegin/sectionEnd is ever touched; everything else in the
// file (or the whole file, if it doesn't exist yet) is the repo owner's.
//
// Unlike the per-file dialects, the managed section is rewritten wholesale
// on every run, so a plain overwrite would silently drop any opt-in
// command's subsection the moment a run doesn't ask for it again (e.g. a
// default run after an earlier all=true run). To keep this non-destructive
// like the file dialects, any heading already present in the existing
// section but not in this run's specs is carried forward unchanged instead
// of being dropped.
func writeAgentsSection(root string, specs []commandSpec, bodies map[string]string) ([]string, error) {
	path := filepath.Join(root, "AGENTS.md")

	existing, err := os.ReadFile(path)
	var content string
	switch {
	case err == nil:
		preserved := parseAgentsHeadings(extractManagedSection(string(existing)))
		section := agentsSection(specs, bodies, preserved)
		content = replaceManagedSection(string(existing), section)
	case os.IsNotExist(err):
		content = agentsSection(specs, bodies, nil)
	default:
		return nil, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return nil, err
	}
	return []string{relToRoot(root, path)}, nil
}

// agentsSection assembles the managed-section body. For each commandSpec
// (in canonical order): if it's in this run's specs, its freshly rendered
// body wins; otherwise, if preserved has a heading match (a subsection an
// earlier run wrote and this one didn't ask for again), that old content is
// kept as-is; otherwise the heading is omitted entirely (never generated).
func agentsSection(specs []commandSpec, bodies map[string]string, preserved map[string]string) string {
	selected := map[string]bool{}
	for _, spec := range specs {
		selected[spec.Heading] = true
	}
	var b strings.Builder
	b.WriteString(sectionBegin + "\n")
	b.WriteString(generatedHeader + "\n\n")
	first := true
	for _, spec := range commandSpecs {
		var body string
		switch {
		case selected[spec.Heading]:
			body = bodies[spec.Template]
		default:
			old, ok := preserved[spec.Heading]
			if !ok {
				continue
			}
			body = old
		}
		if !first {
			b.WriteString("\n")
		}
		first = false
		b.WriteString("## spectackle " + spec.Heading + "\n\n")
		b.WriteString(strings.TrimRight(body, "\n") + "\n")
	}
	b.WriteString(sectionEnd + "\n")
	return b.String()
}

// extractManagedSection returns the raw text of the existing managed
// section (markers included), or "" if AGENTS.md has none yet.
func extractManagedSection(existing string) string {
	start := strings.Index(existing, sectionBegin)
	end := strings.Index(existing, sectionEnd)
	if start == -1 || end == -1 || end < start {
		return ""
	}
	end += len(sectionEnd)
	return existing[start:end]
}

// parseAgentsHeadings splits a managed-section's text (as produced by
// agentsSection) back into heading -> body pairs, so a later run can carry
// forward subsections it isn't regenerating this time. section == ""
// (no prior managed section) yields a nil map — every lookup misses, so
// nothing is preserved, which is correct: there was nothing to preserve.
func parseAgentsHeadings(section string) map[string]string {
	if section == "" {
		return nil
	}
	out := map[string]string{}
	const marker = "## spectackle "
	for _, part := range strings.Split(section, marker)[1:] {
		nl := strings.IndexByte(part, '\n')
		if nl == -1 {
			continue
		}
		heading := strings.TrimSpace(part[:nl])
		out[heading] = strings.TrimRight(part[nl+1:], "\n")
	}
	return out
}

// replaceManagedSection swaps the text between sectionBegin/sectionEnd for
// section, preserving everything else byte-for-byte. No existing managed
// section: append, separated by one blank line from whatever's already
// there (or start fresh if the file was empty).
func replaceManagedSection(existing, section string) string {
	start := strings.Index(existing, sectionBegin)
	end := strings.Index(existing, sectionEnd)
	if start == -1 || end == -1 || end < start {
		trimmed := strings.TrimRight(existing, "\n")
		if trimmed == "" {
			return section
		}
		return trimmed + "\n\n" + section
	}
	end += len(sectionEnd)
	// drop exactly the one newline that immediately followed the old
	// section's end marker — section already supplies its own trailing
	// newline, so keeping both would grow the file by a blank line every gen.
	rest := strings.TrimPrefix(existing[end:], "\n")
	return existing[:start] + section + rest
}

func relToRoot(root, p string) string {
	rel, err := filepath.Rel(root, p)
	if err != nil {
		return p
	}
	return filepath.ToSlash(rel)
}
