package mcpserver

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/jxsl13/spectackle/internal/item"
	"github.com/jxsl13/spectackle/internal/lifecycle"
)

// commands generates harness-native entry points (slash commands / prompt
// files / AGENTS.md sections) from the two templates below, so every
// supported coding-agent harness gets the same two-mode ($ARGUMENTS empty =
// state snapshot, non-empty = full SDD lifecycle) dispatch that
// .claude/commands/spectackle.md pioneered — without hand-maintaining N
// per-harness copies. detect: sniff which harnesses are already wired into
// the repo from filesystem markers. gen: (re)write the dialect files for a
// harness set resolved arg > detection > elicitation (MCP-003 family): the
// user answers a native checkbox form, or — no UI, decline, or a different
// harness — an `adr` item is minted and left open exactly like
// decideAsk (decide.go), never blocking the caller.
type commandsIn struct {
	Op      string   `json:"op" jsonschema:"detect|gen"`
	Harness []string `json:"harness,omitempty" jsonschema:"claude|copilot|codex|kimi — omit to auto-detect"`
}

//go:embed templates/commands/*.tmpl
var commandTemplateFS embed.FS

// commandTemplates parses once at package init: a bad embedded template is a
// build-time bug, not a runtime one.
var commandTemplates = template.Must(template.ParseFS(commandTemplateFS, "templates/commands/*.tmpl"))

// commandsData is the template data — {Binary, Tool} are both "spectackle"
// today; kept as two fields (not one) because the binary name (CLI, `/x-state`
// slash-command stem) and the MCP tool/server name are conceptually distinct
// even though this repo's install happens to give them the same value.
type commandsData struct {
	Binary string
	Tool   string
}

// generatedHeader is stamped into every artifact `commands gen` writes —
// hand-edits belong in the templates, not the generated files.
const generatedHeader = "<!-- generated by spectackle `commands` — edit internal/mcpserver/templates, not this file -->"

// sectionBegin/sectionEnd delimit the managed block commands gen writes into
// AGENTS.md for the codex/kimi dialect — everything outside the markers is
// the repo owner's, never touched.
const (
	sectionBegin = "<!-- spectackle:commands:begin -->"
	sectionEnd   = "<!-- spectackle:commands:end -->"
)

var validHarnesses = map[string]bool{"claude": true, "copilot": true, "codex": true, "kimi": true}

func (s *Server) commands(ctx context.Context, req *mcp.CallToolRequest, in commandsIn) (*mcp.CallToolResult, any, error) {
	switch in.Op {
	case "detect":
		return s.commandsDetect()
	case "gen":
		return s.commandsGen(ctx, req, in)
	}
	return text("! ARG E - op must be detect|gen")
}

// ---- detect ----

// harnessHit is one root-marker match: which harness it identifies and the
// path that triggered it.
type harnessHit struct{ harness, marker string }

// detectHarnesses sniffs the workspace root for each supported harness's
// native marker. AGENTS.md is consumed by both codex and kimi, so its
// presence yields two hits, not one — a repo with only AGENTS.md and no
// .codex/.kimi dirs is still unambiguous about wanting both dialects kept in
// sync.
func detectHarnesses(root string) []harnessHit {
	var hits []harnessHit
	if isDir(filepath.Join(root, ".claude")) {
		hits = append(hits, harnessHit{"claude", ".claude/"})
	}
	if isDir(filepath.Join(root, ".github", "prompts")) {
		hits = append(hits, harnessHit{"copilot", ".github/prompts/"})
	} else if isFile(filepath.Join(root, ".github", "copilot-instructions.md")) {
		hits = append(hits, harnessHit{"copilot", ".github/copilot-instructions.md"})
	}
	if isDir(filepath.Join(root, ".codex")) {
		hits = append(hits, harnessHit{"codex", ".codex/"})
	}
	if isDir(filepath.Join(root, ".kimi")) {
		hits = append(hits, harnessHit{"kimi", ".kimi/"})
	}
	if isFile(filepath.Join(root, "AGENTS.md")) {
		hits = append(hits, harnessHit{"codex", "AGENTS.md"}, harnessHit{"kimi", "AGENTS.md"})
	}
	return hits
}

func isDir(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && fi.IsDir()
}

func isFile(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && !fi.IsDir()
}

func (s *Server) commandsDetect() (*mcp.CallToolResult, any, error) {
	hits := detectHarnesses(s.ws.Dir)
	if len(hits) == 0 {
		return text("nf harness — pass harness=... or answer the decision\n")
	}
	var b strings.Builder
	for _, h := range hits {
		fmt.Fprintf(&b, "h %s %s\n", h.harness, h.marker)
	}
	return text(b.String())
}

// ---- gen ----

const commandsQuestion = "which harnesses should `commands` generate for? (claude, copilot, codex, kimi)"

func (s *Server) commandsGen(ctx context.Context, req *mcp.CallToolRequest, in commandsIn) (*mcp.CallToolResult, any, error) {
	harnesses, err := normalizeHarnesses(in.Harness)
	if err != nil {
		return text("! ARG E - " + err.Error())
	}
	if len(harnesses) == 0 {
		harnesses = dedupHarnessHits(detectHarnesses(s.ws.Dir))
	}
	if len(harnesses) == 0 {
		selected, ok := s.commandsElicit(ctx, req)
		if !ok {
			return s.commandsMintDecision()
		}
		if len(selected) == 0 {
			return text("! ARG E - no harness selected")
		}
		harnesses = selected
	}

	workflowBody, err := renderCommandTemplate("workflow.md.tmpl")
	if err != nil {
		return nil, nil, err
	}
	stateBody, err := renderCommandTemplate("state.md.tmpl")
	if err != nil {
		return nil, nil, err
	}

	var b strings.Builder
	for _, h := range harnesses {
		files, err := writeDialect(s.ws.Dir, h, workflowBody, stateBody)
		if err != nil {
			return nil, nil, err
		}
		for _, f := range files {
			fmt.Fprintf(&b, "ok gen %s %s\n", h, f)
		}
	}
	// codegen, not spec history: one coord event so siblings see it happened
	// in realtime, but no journal write — these files aren't .spectackle state.
	_ = s.cd.Emit("commands", strings.Join(harnesses, ","), s.ws.Dir)
	return text(b.String())
}

// normalizeHarnesses validates and dedupes an explicit harness= argument,
// preserving first-seen order.
func normalizeHarnesses(in []string) ([]string, error) {
	var out []string
	seen := map[string]bool{}
	for _, h := range in {
		h = strings.ToLower(strings.TrimSpace(h))
		if h == "" {
			continue
		}
		if !validHarnesses[h] {
			return nil, fmt.Errorf("unknown harness %q (want claude|copilot|codex|kimi)", h)
		}
		if !seen[h] {
			seen[h] = true
			out = append(out, h)
		}
	}
	return out, nil
}

// dedupHarnessHits collapses detectHarnesses' hits (which may name the same
// harness twice, e.g. AGENTS.md hitting both codex and kimi) to a unique,
// first-seen-order harness list.
func dedupHarnessHits(hits []harnessHit) []string {
	var out []string
	seen := map[string]bool{}
	for _, h := range hits {
		if !seen[h.harness] {
			seen[h.harness] = true
			out = append(out, h.harness)
		}
	}
	return out
}

// commandsElicit renders a native checkbox form (one boolean per harness) —
// the same req.Session.Elicit mechanism elicitSlots (tools.go) and decideAsk
// (decide.go) use — and returns the harnesses the user checked. ok is false
// on any non-accept outcome (no elicitation capability, decline, cancel,
// transport error): the caller falls back to minting an adr item instead of
// blocking.
func (s *Server) commandsElicit(ctx context.Context, req *mcp.CallToolRequest) ([]string, bool) {
	props := map[string]any{
		"claude":  map[string]any{"type": "boolean", "description": "Claude Code — .claude/commands/*.md"},
		"copilot": map[string]any{"type": "boolean", "description": "GitHub Copilot — .github/prompts/*.prompt.md"},
		"codex":   map[string]any{"type": "boolean", "description": "Codex — AGENTS.md managed section"},
		"kimi":    map[string]any{"type": "boolean", "description": "Kimi — AGENTS.md managed section"},
	}
	res, err := req.Session.Elicit(ctx, &mcp.ElicitParams{
		Message: "spectackle: " + commandsQuestion,
		RequestedSchema: map[string]any{
			"type": "object", "properties": props,
		},
	})
	if err != nil || res.Action != "accept" {
		return nil, false
	}
	var out []string
	for _, h := range []string{"claude", "copilot", "codex", "kimi"} {
		if b, _ := res.Content[h].(bool); b {
			out = append(out, h)
		}
	}
	return out, true
}

// commandsMintDecision is the elicitation-declined/no-UI fallback: mint a
// free-text `adr` item and leave it open (state=submitted), exactly
// like decideAsk (decide.go) does when its own elicitation attempt fails —
// duplicated minimally here rather than calling decideAsk itself, since that
// would fire a second, differently-shaped elicitation round after ours
// already came back empty.
func (s *Server) commandsMintDecision() (*mcp.CallToolResult, any, error) {
	body := "kind: text\noptions: free text — comma-separated subset of claude,copilot,codex,kimi"
	d, err := lifecycle.Draft(s.ws, s.minter(), "adr", commandsQuestion, body, "", "", nil)
	if err != nil {
		return text("! ARG E - " + err.Error())
	}
	if _, err := lifecycle.Move(s.ws, d.ID, item.StateSubmitted, ""); err != nil {
		return nil, nil, err
	}
	s.scan.MarkDirty()
	_ = s.cd.Emit("decide", d.ID, "ask "+commandsQuestion)
	return text(fmt.Sprintf("need decision %s %s\n", d.ID, commandsQuestion))
}

// ---- template rendering + per-dialect writers ----

func renderCommandTemplate(name string) (string, error) {
	var buf bytes.Buffer
	data := commandsData{Binary: "spectackle", Tool: "spectackle"}
	if err := commandTemplates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// writeDialect dispatches to the per-harness writer and returns the
// repo-relative paths written, for the `ok gen <harness> <path>` result
// lines.
func writeDialect(root, harness, workflowBody, stateBody string) ([]string, error) {
	switch harness {
	case "claude":
		return writeClaudeDialect(root, workflowBody, stateBody)
	case "copilot":
		return writeCopilotDialect(root, workflowBody, stateBody)
	case "codex", "kimi":
		return writeAgentsSection(root, workflowBody, stateBody)
	}
	return nil, fmt.Errorf("unknown harness %q", harness)
}

// writeClaudeDialect regenerates .claude/commands/spectackle.md and
// spectackle-state.md — same frontmatter shape (description:) the
// hand-written originals carried, plus the generated-header comment.
func writeClaudeDialect(root, workflowBody, stateBody string) ([]string, error) {
	dir := filepath.Join(root, ".claude", "commands")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	workflow := "---\ndescription: spectackle entry point — bare = state snapshot, with a requirement = full SDD lifecycle\n---\n\n" +
		generatedHeader + "\n\n" + workflowBody
	state := "---\ndescription: Render the current spectackle state (explicit alias for bare /spectackle)\n---\n\n" +
		generatedHeader + "\n\n" + stateBody
	wf := filepath.Join(dir, "spectackle.md")
	sf := filepath.Join(dir, "spectackle-state.md")
	if err := os.WriteFile(wf, []byte(workflow), 0o644); err != nil {
		return nil, err
	}
	if err := os.WriteFile(sf, []byte(state), 0o644); err != nil {
		return nil, err
	}
	return []string{relToRoot(root, wf), relToRoot(root, sf)}, nil
}

// writeCopilotDialect writes .github/prompts/spectackle.prompt.md and
// spectackle-state.prompt.md with GitHub Copilot's `mode: agent` frontmatter.
func writeCopilotDialect(root, workflowBody, stateBody string) ([]string, error) {
	dir := filepath.Join(root, ".github", "prompts")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	workflow := "---\nmode: agent\n---\n\n" + generatedHeader + "\n\n" + workflowBody
	state := "---\nmode: agent\n---\n\n" + generatedHeader + "\n\n" + stateBody
	wf := filepath.Join(dir, "spectackle.prompt.md")
	sf := filepath.Join(dir, "spectackle-state.prompt.md")
	if err := os.WriteFile(wf, []byte(workflow), 0o644); err != nil {
		return nil, err
	}
	if err := os.WriteFile(sf, []byte(state), 0o644); err != nil {
		return nil, err
	}
	return []string{relToRoot(root, wf), relToRoot(root, sf)}, nil
}

// writeAgentsSection creates or updates AGENTS.md's spectackle-managed
// section (codex and kimi share it — both harnesses consume AGENTS.md) with
// both command descriptions. Only the text between sectionBegin/sectionEnd
// is ever touched; everything else in the file (or the whole file, if it
// doesn't exist yet) is the repo owner's.
func writeAgentsSection(root, workflowBody, stateBody string) ([]string, error) {
	path := filepath.Join(root, "AGENTS.md")
	section := agentsSection(workflowBody, stateBody)

	existing, err := os.ReadFile(path)
	var content string
	switch {
	case err == nil:
		content = replaceManagedSection(string(existing), section)
	case os.IsNotExist(err):
		content = section
	default:
		return nil, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return nil, err
	}
	return []string{relToRoot(root, path)}, nil
}

func agentsSection(workflowBody, stateBody string) string {
	var b strings.Builder
	b.WriteString(sectionBegin + "\n")
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("## spectackle workflow\n\n")
	b.WriteString(strings.TrimRight(workflowBody, "\n") + "\n")
	b.WriteString("\n## spectackle state\n\n")
	b.WriteString(strings.TrimRight(stateBody, "\n") + "\n")
	b.WriteString(sectionEnd + "\n")
	return b.String()
}

// replaceManagedSection swaps the text between sectionBegin/sectionEnd for
// section, preserving everything else byte-for-byte. No existing managed
// section: append, separated by one blank line from whatever's already
// there (or start fresh if the file was empty).
func replaceManagedSection(existing, section string) string {
	start := strings.Index(existing, sectionBegin)
	end := strings.Index(existing, sectionEnd)
	if start == -1 || end == -1 || end < start {
		trimmed := strings.TrimRight(existing, "\n")
		if trimmed == "" {
			return section
		}
		return trimmed + "\n\n" + section
	}
	end += len(sectionEnd)
	// drop exactly the one newline that immediately followed the old
	// section's end marker — section already supplies its own trailing
	// newline, so keeping both would grow the file by a blank line every gen.
	rest := strings.TrimPrefix(existing[end:], "\n")
	return existing[:start] + section + rest
}

func relToRoot(root, p string) string {
	rel, err := filepath.Rel(root, p)
	if err != nil {
		return p
	}
	return filepath.ToSlash(rel)
}
