package bench

// The agent-judge stage (P-01KYDP stage 4): a scripted driver cannot get
// lost, an agent can — so guidance quality is judged by handing a FRESH,
// independent agent a metered fixture and a fixed brief, then scoring the
// run mechanically. The binary only PREPARES (fixture, brief, metering
// shim) and SCORES (goal states reached, bytes consumed); spawning the
// agent is the orchestrator's job and deliberately lives outside this
// repository, so the score stays comparable across server builds: brief
// and fixture are identical by construction.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// judgeTaskTitle and judgeBugTitle are the goal markers the score looks
// for. They are constants shared by brief and scorer: a drifted pair would
// judge agents against goals the brief never stated.
const (
	judgeTaskTitle = "agent judge run"
	judgeBugTitle  = "bogus report"
)

// agentBrief is the FIXED task brief. Tool names only, zero semantic
// coaching: how the tools work must come from the server's own texts —
// instructions, results, refusals — because those texts are what is being
// judged. Coaching in the brief would mask exactly the guidance gaps the
// judge exists to find.
const agentBrief = `You operate a spec-driven-development workflow through a CLI.

Workspace: %s
Command shape, the ONLY allowed way to act:
  %s call -root %s <tool> '<json-arguments>'

Available tool names: state, draft, move, get, find, grill, check, rule, decide, research.
No other documentation is provided; the tool outputs themselves guide you.

Goals, in any order:
1. A task titled "` + judgeTaskTitle + `" exists and ends in state archived.
2. A bug titled "` + judgeBugTitle + `" exists and ends in state rejected.
3. A final check call reports ok.

Start with the state tool. When all goals are met, stop and output exactly DONE.
`

// trickyTaskTitle and trickyRuleStem are the tricky scenario's goal
// markers, shared by brief and scorer like the basic pair.
const (
	trickyTaskTitle = "stubborn rework loop"
	trickyRuleStem  = "JUDGE-API"
)

// trickyBrief sends the agent through the side states the basic scenario
// never touches (T-01KYE4): rule slot elicitation and lint, the reopen
// counter, the ROUNDS escalation into blocked, and the decide exit. Same
// zero-coaching discipline: tool names only, the server's own texts must
// carry the agent through — those texts are what is being judged.
const trickyBrief = `You operate a spec-driven-development workflow through a CLI.

Workspace: %s
Command shape, the ONLY allowed way to act:
  %s call -root %s <tool> '<json-arguments>'

Available tool names: state, draft, move, get, find, grill, check, rule, decide, research.
No other documentation is provided; the tool outputs themselves guide you.

Goals, in order:
1. A rule with stem "` + trickyRuleStem + `" exists in directory "api". Its response clause must name a concrete number.
2. A task titled "` + trickyTaskTitle + `" is driven to done, reopened to active, driven to done again, and reopened again — keep going until the server refuses to continue this loop and points you at a decision; resolve that decision choosing rescope, so the task ends in state draft.
3. A final check call reports no findings marked E.

Start with the state tool. When all goals are met, stop and output exactly DONE.
`

// meterShim passes every call through to the real binary while appending
// one line per call to meter.log: <bytes> <exit> <argv>. Stdout and stderr
// are metered together — both reach the agent's context, so both are cost.
const meterShim = `#!/bin/sh
# generated by spectackle bench -agent-prep; passes through to the real
# binary and meters output bytes per call.
REAL=%q
METER=%q
OUT=$("$REAL" "$@" 2>&1)
rc=$?
printf '%%s\n' "$OUT"
printf '%%d %%d %%s\n' "${#OUT}" "$rc" "$*" >> "$METER"
exit $rc
`

// AgentPrep builds a judge workspace in dir: the seeded v2 fixture, the
// fixed brief, and the metering shim wrapping bin. It prints nothing —
// callers report the returned paths.
//
// withManifest prepends the composed connect-time manifest to the brief —
// the judge then simulates an MCP session, which reads exactly that text at
// initialize — and records its byte count in a manifest.size sidecar so the
// scorer can report the session-shaped cost next to the tool diet
// (T-01KYE3X: whether connect-time guidance BUYS anything is measured, not
// assumed). Without the flag the brief is byte-identical to before.
func AgentPrep(bin, dir string, withManifest bool, scenario string) (briefPath, shimPath string, err error) {
	if err := Fixture(dir); err != nil {
		return "", "", err
	}
	if err := Seed(bin, dir); err != nil {
		return "", "", err
	}
	shimPath = filepath.Join(dir, "meter.sh")
	briefPath = filepath.Join(dir, "brief.md")
	meterLog := filepath.Join(dir, "meter.log")

	if err := os.WriteFile(shimPath, fmt.Appendf(nil, meterShim, bin, meterLog), 0o755); err != nil {
		return "", "", err
	}
	var brief string
	switch scenario {
	case "", "basic":
		brief = fmt.Sprintf(agentBrief, dir, shimPath, dir)
	case "tricky":
		brief = fmt.Sprintf(trickyBrief, dir, shimPath, dir)
		// The scorer branches on this sidecar: tricky goals are judged by
		// different criteria, and inferring the scenario from brief prose
		// would couple the scorer to wording.
		if err := os.WriteFile(filepath.Join(dir, "scenario"), []byte("tricky\n"), 0o644); err != nil {
			return "", "", err
		}
	default:
		return "", "", fmt.Errorf("bench agent-prep: unknown scenario %q (basic|tricky)", scenario)
	}
	if withManifest {
		out, err := exec.Command(bin, "manifest").Output()
		if err != nil {
			return "", "", fmt.Errorf("bench agent-prep: manifest: %w", err)
		}
		brief = "Connect-time server instructions (what an MCP session receives at initialize):\n\n" +
			string(out) + "\n---\n\n" + brief
		if err := os.WriteFile(filepath.Join(dir, "manifest.size"),
			fmt.Appendf(nil, "%d\n", len(out)), 0o644); err != nil {
			return "", "", err
		}
	}
	if err := os.WriteFile(briefPath, []byte(brief), 0o644); err != nil {
		return "", "", err
	}
	return briefPath, shimPath, nil
}

// AgentScore judges a completed run in dir mechanically. Verdict rules:
// both goal items in their goal states, and the final check E-free (the
// B-01KYDM taxonomy: W findings are environmental degradations, E findings
// are failures). Bytes come from meter.log — the agent's whole tool-output
// diet, including every refusal and retry it needed.
type AgentScore struct {
	Calls     int
	Bytes     int
	Tokens    int
	TaskState string // state of the judge task, "" if absent
	BugState  string // state of the judge bug, "" if absent
	CheckOK   bool
	Valid     bool
	// ManifestBytes is the connect-time manifest's size when the run was
	// prepped -with-manifest (read from the manifest.size sidecar), zero
	// otherwise. Kept OUT of Bytes: the aggregate spreads compare tool
	// diets, and folding a per-session constant into them would blur
	// exactly the wandering signal they exist to show.
	ManifestBytes int
	// Scenario is "basic" or "tricky" (from the scenario sidecar); RuleOK
	// is the tricky rule goal, DecideOK the tricky decide-answer proof.
	Scenario string
	RuleOK   bool
	DecideOK bool
}

func ScoreAgentRun(bin, dir string) (AgentScore, error) {
	var sc AgentScore

	raw, err := os.ReadFile(filepath.Join(dir, "meter.log"))
	if err != nil {
		return sc, fmt.Errorf("bench agent-score: no meter.log — did the agent use the shim? %w", err)
	}
	for line := range strings.SplitSeq(strings.TrimSpace(string(raw)), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		n, err := strconv.Atoi(fields[0])
		if err != nil {
			continue
		}
		sc.Calls++
		sc.Bytes += n
	}
	sc.Tokens = sc.Bytes / 4
	if raw, err := os.ReadFile(filepath.Join(dir, "manifest.size")); err == nil {
		if n, err := strconv.Atoi(strings.TrimSpace(string(raw))); err == nil {
			sc.ManifestBytes = n
		}
	}

	checkOut, _, err := callOnce(bin, dir, "check", "{}")
	if err != nil {
		return sc, err
	}
	sc.CheckOK = strings.TrimSpace(checkOut) == "ok" || !strings.Contains(checkOut, " E ")

	if scen, err := os.ReadFile(filepath.Join(dir, "scenario")); err == nil && strings.TrimSpace(string(scen)) == "tricky" {
		return scoreTricky(bin, dir, sc, string(raw))
	}

	// Basic scenario. Goal states are judged through the same tool surface
	// the agent used: archived and rejected items leave work.md entirely
	// (the journal holds the tombstone and the reject snapshot), so the
	// history and rejection scopes of find are the authoritative — and
	// public — answer.
	histOut, _, err := callOnce(bin, dir, "find", fmt.Sprintf(`{"q":%q,"scope":"history"}`, judgeTaskTitle))
	if err != nil {
		return sc, err
	}
	if strings.Contains(histOut, " archive ") && strings.Contains(histOut, judgeTaskTitle) {
		sc.TaskState = "archived"
	}
	rejOut, _, err := callOnce(bin, dir, "find", fmt.Sprintf(`{"q":%q,"scope":"rejection"}`, judgeBugTitle))
	if err != nil {
		return sc, err
	}
	if strings.Contains(rejOut, " reject ") && strings.Contains(rejOut, judgeBugTitle) {
		sc.BugState = "rejected"
	}

	sc.Valid = sc.TaskState == "archived" && sc.BugState == "rejected" && sc.CheckOK
	return sc, nil
}

// scoreTricky judges the side-state scenario (T-01KYE4). Ground truths the
// criteria rest on, probed before this was built: find scope=history shows
// only create and archive events, so the reopen cycle is NOT scorable there
// — instead the chain is proven by its endpoints: the task ends at draft
// (only the rescope exit lands there from blocked) and the meter shows a
// successful decide call answering it (an agent cannot legally answer a
// decision that was never minted, and only the exhausted reopen loop mints
// one for this task).
func scoreTricky(bin, dir string, sc AgentScore, meterRaw string) (AgentScore, error) {
	ruleOut, _, err := callOnce(bin, dir, "find", fmt.Sprintf(`{"q":%q,"scope":"rule"}`, trickyRuleStem))
	if err != nil {
		return sc, err
	}
	ruleOK := strings.Contains(ruleOut, trickyRuleStem)

	// The task's end state comes from state's live item listing: draft
	// items are present there (only archived/rejected tombstone away).
	stateOut, _, err := callOnce(bin, dir, "state", "{}")
	if err != nil {
		return sc, err
	}
	for line := range strings.SplitSeq(stateOut, "\n") {
		if strings.Contains(line, trickyTaskTitle) && strings.Contains(line, " draft ") {
			sc.TaskState = "draft"
		}
	}

	for line := range strings.SplitSeq(strings.TrimSpace(meterRaw), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 4 && fields[1] == "0" && strings.Contains(line, " decide ") && strings.Contains(line, "answer") {
			sc.DecideOK = true
		}
	}
	sc.Scenario = "tricky"
	sc.RuleOK = ruleOK
	sc.Valid = ruleOK && sc.TaskState == "draft" && sc.DecideOK && sc.CheckOK
	return sc, nil
}

// AgentReport renders one judged run as dense agent lines.
func AgentReport(sc AgentScore) string {
	var b strings.Builder
	fmt.Fprintf(&b, "agent calls=%d bytes=%d ~%d tokens\n", sc.Calls, sc.Bytes, sc.Tokens)
	if sc.ManifestBytes > 0 {
		fmt.Fprintf(&b, "agent session=%dB (manifest %d + tools %d)\n", sc.ManifestBytes+sc.Bytes, sc.ManifestBytes, sc.Bytes)
	}
	if sc.Scenario == "tricky" {
		fmt.Fprintf(&b, "agent goal rule=%v task=%s decide=%v check=%v\n", sc.RuleOK, orAbsent(sc.TaskState), sc.DecideOK, sc.CheckOK)
	} else {
		fmt.Fprintf(&b, "agent goal task=%s bug=%s check=%v\n", orAbsent(sc.TaskState), orAbsent(sc.BugState), sc.CheckOK)
	}
	if sc.Valid {
		b.WriteString("agent verdict: valid — goals reached\n")
	} else {
		b.WriteString("agent verdict: INVALID — goals not reached\n")
	}
	return b.String()
}

func orAbsent(s string) string {
	if s == "" {
		return "absent"
	}
	return s
}

// AggregateReport renders n judged runs: per-run lines prefixed with their
// label, then one summary. One run cannot carry a verdict — at one build,
// valid runs have spanned 17-46 calls and 2279-5896 bytes — so the spread
// IS the signal. Median over mean: a single wanderer must not drag the
// central figure. AllValid gates the caller's exit code: a text change that
// makes one judge in three fail is a regression however good the median
// looks.
func AggregateReport(labels []string, scores []AgentScore) (string, bool) {
	var b strings.Builder
	allValid := true
	calls := make([]int, 0, len(scores))
	bytes := make([]int, 0, len(scores))
	valid := 0
	for i, sc := range scores {
		for line := range strings.SplitSeq(strings.TrimRight(AgentReport(sc), "\n"), "\n") {
			fmt.Fprintf(&b, "%s %s\n", labels[i], line)
		}
		calls = append(calls, sc.Calls)
		bytes = append(bytes, sc.Bytes)
		if sc.Valid {
			valid++
		} else {
			allValid = false
		}
	}
	fmt.Fprintf(&b, "agents n=%d valid=%d/%d calls=%s bytes=%s\n",
		len(scores), valid, len(scores), spread(calls), spread(bytes))
	return b.String(), allValid
}

// spread renders min/median/max. Even-length medians take the lower middle:
// judge counts are tiny, and a half-value would suggest precision the
// sample cannot carry.
func spread(vals []int) string {
	s := append([]int(nil), vals...)
	sort.Ints(s)
	return fmt.Sprintf("%d/%d/%d", s[0], s[(len(s)-1)/2], s[len(s)-1])
}
