package bench

// The agent-judge stage (P-01KYDP stage 4): a scripted driver cannot get
// lost, an agent can — so guidance quality is judged by handing a FRESH,
// independent agent a metered fixture and a fixed brief, then scoring the
// run mechanically. The binary only PREPARES (fixture, brief, metering
// shim) and SCORES (goal states reached, bytes consumed); spawning the
// agent is the orchestrator's job and deliberately lives outside this
// repository, so the score stays comparable across server builds: brief
// and fixture are identical by construction.

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// judgeTaskTitle and judgeBugTitle are the goal markers the score looks
// for. They are constants shared by brief and scorer: a drifted pair would
// judge agents against goals the brief never stated.
const (
	judgeTaskTitle = "agent judge run"
	judgeBugTitle  = "bogus report"
)

// agentBrief is the FIXED task brief. Tool names only, zero semantic
// coaching: how the tools work must come from the server's own texts —
// instructions, results, refusals — because those texts are what is being
// judged. Coaching in the brief would mask exactly the guidance gaps the
// judge exists to find.
const agentBrief = `You operate a spec-driven-development workflow through a CLI.

Workspace: %s
Command shape, the ONLY allowed way to act:
  %s call -root %s <tool> '<json-arguments>'

Available tool names: state, draft, move, get, find, grill, check, rule, decide, research.
No other documentation is provided; the tool outputs themselves guide you.

Goals, in any order:
1. A task titled "` + judgeTaskTitle + `" exists and ends in state archived.
2. A bug titled "` + judgeBugTitle + `" exists and ends in state rejected.
3. A final check call reports ok.

Start with the state tool. When all goals are met, stop and output exactly DONE.
`

// meterShim passes every call through to the real binary while appending
// one line per call to meter.log: <bytes> <exit> <argv>. Stdout and stderr
// are metered together — both reach the agent's context, so both are cost.
const meterShim = `#!/bin/sh
# generated by spectackle bench -agent-prep; passes through to the real
# binary and meters output bytes per call.
REAL=%q
METER=%q
OUT=$("$REAL" "$@" 2>&1)
rc=$?
printf '%%s\n' "$OUT"
printf '%%d %%d %%s\n' "${#OUT}" "$rc" "$*" >> "$METER"
exit $rc
`

// AgentPrep builds a judge workspace in dir: the seeded v2 fixture, the
// fixed brief, and the metering shim wrapping bin. It prints nothing —
// callers report the returned paths.
func AgentPrep(bin, dir string) (briefPath, shimPath string, err error) {
	if err := Fixture(dir); err != nil {
		return "", "", err
	}
	if err := Seed(bin, dir); err != nil {
		return "", "", err
	}
	shimPath = filepath.Join(dir, "meter.sh")
	briefPath = filepath.Join(dir, "brief.md")
	meterLog := filepath.Join(dir, "meter.log")

	if err := os.WriteFile(shimPath, fmt.Appendf(nil, meterShim, bin, meterLog), 0o755); err != nil {
		return "", "", err
	}
	brief := fmt.Sprintf(agentBrief, dir, shimPath, dir)
	if err := os.WriteFile(briefPath, []byte(brief), 0o644); err != nil {
		return "", "", err
	}
	return briefPath, shimPath, nil
}

// AgentScore judges a completed run in dir mechanically. Verdict rules:
// both goal items in their goal states, and the final check E-free (the
// B-01KYDM taxonomy: W findings are environmental degradations, E findings
// are failures). Bytes come from meter.log — the agent's whole tool-output
// diet, including every refusal and retry it needed.
type AgentScore struct {
	Calls     int
	Bytes     int
	Tokens    int
	TaskState string // state of the judge task, "" if absent
	BugState  string // state of the judge bug, "" if absent
	CheckOK   bool
	Valid     bool
}

func ScoreAgentRun(bin, dir string) (AgentScore, error) {
	var sc AgentScore

	raw, err := os.ReadFile(filepath.Join(dir, "meter.log"))
	if err != nil {
		return sc, fmt.Errorf("bench agent-score: no meter.log — did the agent use the shim? %w", err)
	}
	for line := range strings.SplitSeq(strings.TrimSpace(string(raw)), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		n, err := strconv.Atoi(fields[0])
		if err != nil {
			continue
		}
		sc.Calls++
		sc.Bytes += n
	}
	sc.Tokens = sc.Bytes / 4

	// Goal states are judged through the same tool surface the agent used:
	// archived and rejected items leave work.md entirely (the journal holds
	// the tombstone and the reject snapshot), so the history and rejection
	// scopes of find are the authoritative — and public — answer.
	histOut, _, err := callOnce(bin, dir, "find", fmt.Sprintf(`{"q":%q,"scope":"history"}`, judgeTaskTitle))
	if err != nil {
		return sc, err
	}
	if strings.Contains(histOut, " archive ") && strings.Contains(histOut, judgeTaskTitle) {
		sc.TaskState = "archived"
	}
	rejOut, _, err := callOnce(bin, dir, "find", fmt.Sprintf(`{"q":%q,"scope":"rejection"}`, judgeBugTitle))
	if err != nil {
		return sc, err
	}
	if strings.Contains(rejOut, " reject ") && strings.Contains(rejOut, judgeBugTitle) {
		sc.BugState = "rejected"
	}

	checkOut, _, err := callOnce(bin, dir, "check", "{}")
	if err != nil {
		return sc, err
	}
	sc.CheckOK = strings.TrimSpace(checkOut) == "ok" || !strings.Contains(checkOut, " E ")

	sc.Valid = sc.TaskState == "archived" && sc.BugState == "rejected" && sc.CheckOK
	return sc, nil
}

// AgentReport renders one judged run as dense agent lines.
func AgentReport(sc AgentScore) string {
	var b strings.Builder
	fmt.Fprintf(&b, "agent calls=%d bytes=%d ~%d tokens\n", sc.Calls, sc.Bytes, sc.Tokens)
	fmt.Fprintf(&b, "agent goal task=%s bug=%s check=%v\n", orAbsent(sc.TaskState), orAbsent(sc.BugState), sc.CheckOK)
	if sc.Valid {
		b.WriteString("agent verdict: valid — goals reached\n")
	} else {
		b.WriteString("agent verdict: INVALID — goals not reached\n")
	}
	return b.String()
}

func orAbsent(s string) string {
	if s == "" {
		return "absent"
	}
	return s
}
