// Package corpus deterministically generates a synthetic C corpus used as
// the parity/latency test bed for the wasm-vs-cgo tree-sitter PoC (T-0040).
// Generation is seeded math/rand only (no time, no map iteration order in
// the output path), so Generate(seed) is byte-for-byte reproducible — see
// gen_test.go.
package corpus

import (
	"fmt"
	"math/rand"
	"sort"
	"strings"
)

// Counts, per the T-0040 brief: 1000 functions with bodies, 100
// structs/unions/enums (typedef'd and not), 50 function-like macros, spread
// over ~50 .c/.h files.
const (
	NumFiles     = 50
	NumFunctions = 1000
	NumTypes     = 100
	NumMacros    = 50
)

var (
	nounWords = []string{
		"buffer", "vector", "matrix", "handle", "context", "worker", "queue",
		"stack", "frame", "socket", "stream", "cursor", "cache", "block",
		"segment", "region", "table", "index", "pool", "graph", "node",
		"edge", "token", "lexer", "parser", "encoder", "decoder", "filter",
		"channel", "pipe",
	}
	verbWords = []string{
		"init", "create", "destroy", "alloc", "free", "reset", "update",
		"compute", "resolve", "flush", "commit", "load", "store", "merge",
		"split", "encode", "decode", "validate", "normalize", "compress",
	}
	typeKeywords = []string{"struct", "union", "enum"}
	ctypes       = []string{"int", "float", "double", "char", "long", "unsigned int", "size_t"}
)

// Generate deterministically builds the synthetic C corpus for the given
// seed and returns it as relative-path -> file-bytes. Same seed, same
// output, always (SPX-GRA-001-style determinism, mirrored here for the PoC
// oracle to be trustworthy).
func Generate(seed int64) map[string][]byte {
	rng := rand.New(rand.NewSource(seed))

	files := make([]*strings.Builder, NumFiles)
	names := make([]string, NumFiles)
	for i := range files {
		files[i] = &strings.Builder{}
		ext := ".c"
		if i%5 == 0 { // 1 in 5 files is a header
			ext = ".h"
		}
		names[i] = fmt.Sprintf("synth_%02d%s", i, ext)
		fmt.Fprintf(files[i], "/* synth_%02d%s — generated by poc/wasmparse/corpus, seed-deterministic */\n", i, ext)
		fmt.Fprintf(files[i], "#include <stddef.h>\n\n")
	}

	// Function-like macros, ~1 per file.
	for i := 0; i < NumMacros; i++ {
		fi := i % NumFiles
		name := fmt.Sprintf("MACRO_%s_%d", strings.ToUpper(pick(rng, verbWords)), i)
		fmt.Fprintf(files[fi], "#define %s(a, b) ((a) > (b) ? (a) : (b))\n", name)
	}
	for _, b := range files {
		b.WriteString("\n")
	}

	// Structs/unions/enums, ~2 per file, alternating typedef'd and plain.
	for i := 0; i < NumTypes; i++ {
		fi := i % NumFiles
		kw := typeKeywords[i%len(typeKeywords)]
		name := fmt.Sprintf("%s_t%d", titleCase(pick(rng, nounWords)), i)
		typedefd := i%2 == 0
		writeType(files[fi], kw, name, typedefd, rng)
	}
	for _, b := range files {
		b.WriteString("\n")
	}

	// Functions with bodies, ~20 per file, with if/for/while/switch bait
	// inside bodies (indented — never matches the col0-anchored cSpec
	// regex, and must not be mis-picked-up as top-level defs by the
	// tree-sitter side either).
	for i := 0; i < NumFunctions; i++ {
		fi := i % NumFiles
		ret := ctypes[i%len(ctypes)]
		name := fmt.Sprintf("%s_%s_%d", pick(rng, verbWords), pick(rng, nounWords), i)
		writeFunction(files[fi], ret, name, i, rng)
	}

	out := make(map[string][]byte, NumFiles)
	for i, b := range files {
		out[names[i]] = []byte(b.String())
	}
	return out
}

// SortedNames returns the corpus's relative file names in a stable,
// deterministic order (useful for tests and for reproducible measurement
// runs).
func SortedNames(files map[string][]byte) []string {
	out := make([]string, 0, len(files))
	for k := range files {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func pick(rng *rand.Rand, words []string) string {
	return words[rng.Intn(len(words))]
}

// titleCase upper-cases just the first byte of s (s is always a plain
// lowercase ASCII word from nounWords/verbWords here, so this is a
// deliberately narrow replacement for the deprecated strings.Title).
func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func writeType(b *strings.Builder, kw, name string, typedefd bool, rng *rand.Rand) {
	fieldCount := 2 + rng.Intn(3)
	if typedefd {
		fmt.Fprintf(b, "typedef %s %s {\n", kw, name)
	} else {
		fmt.Fprintf(b, "%s %s {\n", kw, name)
	}
	for f := 0; f < fieldCount; f++ {
		if kw == "enum" {
			fmt.Fprintf(b, "    %s_MEMBER_%d,\n", strings.ToUpper(name), f)
		} else {
			fmt.Fprintf(b, "    %s field_%d;\n", ctypes[f%len(ctypes)], f)
		}
	}
	if typedefd {
		fmt.Fprintf(b, "} %s;\n", name)
	} else {
		b.WriteString("};\n")
	}
}

// writeFunction emits a single-line signature (required for cSpec's
// col0-anchored, single-line regex to have any chance of matching) followed
// by a body containing if/for/while/switch control flow as negative bait:
// every one of those lines is indented, so it must never be picked up as a
// top-level definition by either parser.
func writeFunction(b *strings.Builder, ret, name string, seedIdx int, rng *rand.Rand) {
	fmt.Fprintf(b, "%s %s(int n, float a, const float *x, float *y) {\n", ret, name)
	fmt.Fprintf(b, "    int i;\n")
	switch seedIdx % 4 {
	case 0:
		fmt.Fprintf(b, "    if (n > 0) {\n        y[0] = a * x[0];\n    }\n")
	case 1:
		fmt.Fprintf(b, "    for (i = 0; i < n; i++) {\n        y[i] = a * x[i] + y[i];\n    }\n")
	case 2:
		fmt.Fprintf(b, "    while (n > 0) {\n        n--;\n    }\n")
	case 3:
		fmt.Fprintf(b, "    switch (n) {\n    case 0:\n        return (%s)0;\n    default:\n        break;\n    }\n", ret)
	}
	if ret == "void" {
		b.WriteString("    return;\n")
	} else {
		fmt.Fprintf(b, "    return (%s)0;\n", ret)
	}
	b.WriteString("}\n\n")
	_ = rng // reserved for future body-shape variance; kept deterministic today
}
